# Changes here will be overwritten by Copier
_commit: 0.10.2
_src_path: gh:pawamoy/copier-pdm
author_email: gdouzas@icloud.com
author_fullname: Georgios Douzas
author_username: georgedouzas
copyright_date: '2021'
copyright_holder: Georgios Douzas
copyright_holder_email: gdouzas@icloud.com
copyright_license: MIT License
project_description: MapIntel is a system for acquiring intelligence from vast collections
    of text data by representing each document as a multidimensional vector that captures
    its own semantics. The system is designed to handle complex Natural Language queries
    and visual exploration of the corpus.
project_name: mapintel
python_package_command_line_name: mapintel
python_package_distribution_name: mapintel
python_package_import_name: mapintel
repository_name: MapIntel
repository_namespace: NOVA-IMS-Innovation-and-Analytics-Lab
repository_provider: github.com
use_precommit: false

